name: Deploy to stage

on:
  push:
    branches:
      - main

run-name: "Deploy to stage ${{ github.event.pull_request.title }}"

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: .
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: splittyapp/stage-splitty-fe:latest
          build-args: |
            "NEXT_PUBLIC_SERVER_URL=https://backend-stage.splitty.digital"

  deployment:
    name: deployment  stage
    needs: [build ]
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGE_PRIVATE_KEY }}

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST_STAGE }} << EOF
            cd /root/app
            ./deploy-frontend.sh
          EOF